### ISSUE TITLE
No passive IR pointer

### ISSUE THREAD

**Issue by Foxlum** [EZForever/UDPMote#1]
There is currently no passive IR pointer emulation, could that be done as a option compared to actively touching the screen to move the pointer around.

**Comment by EZForever** [comment]
If you are using Dolphin, IR emulation via motion inputs is already supported. Just enable "Point" emulation under "Motion Input" tab and you are good to go.

![image](https://user-images.githubusercontent.com/34133756/124532913-094b3c00-de44-11eb-941d-4a5d016c760e.png)

**Comment by Foxlum** [comment]
@EZForever though unfortunately, there is no option for the UI with buttons only.

**Comment by EZForever** [comment]
Um, I don't think an option for specifically *removing* a UI feature makes sense, since the feature is not causing any bug or inconvinence.

Anyway, this issue is a non-issue and will be closed.
